name: Rust

on:
  push:
    branches: [ "rust" ]
  pull_request:
    branches: [ "rust" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/deadlocked
        tag_name: deadlocked
        name: deadlocked
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
